### PR TITLE
Bump up version dateutil version

### PR DESCRIPTION
**Pull request by balthasarschuess**

### CODE REVIEW

**Review by hadiyouness10 — COMMENTED** [review]
I don't see a problem upgrading the package, but why do we need it?

**Comment by balthasarschuess** [comment]
> I don't see a problem upgrading the package, but why do we need it?

Sorry should have written the reason yesterday directly.
Basically we want to upgrade our docker images to ubuntu 22.04 and with it a bunch of dependencies.
https://github.com/logivations/deep_cv/pull/4235
As a consequence we require `python_dateutils==2.8.2` which clashes with `label-studios` dependency.
Instead of bumping up fully we could also do something like `>=2.8.1`

**Comment by hadiyouness10** [comment]
> > I don't see a problem upgrading the package, but why do we need it?
> 
> Sorry should have written the reason yesterday directly. Basically we want to upgrade our docker images to ubuntu 22.04 and with it a bunch of dependencies. [logivations/deep_cv#4235](https://github.com/logivations/deep_cv/pull/4235) As a consequence we require `python_dateutils==2.8.2` which clashes with `label-studios` dependency. Instead of bumping up fully we could also do something like `>=2.8.1`

No worries:) sure, looks good to me

**Review by hadiyouness10 — APPROVED** [review]

**Comment by balthasarschuess** [comment]
Ok, then I'll merge this

**Pull request merged**
